//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdMst
    {
        public int AdMstID { get; set; }
        public Nullable<int> AdCode { get; set; }
        public string AdName { get; set; }
        public byte[] AdImage { get; set; }
        public Nullable<int> NotificationType { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
