//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchTypeMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BranchTypeMst()
        {
            this.Med_PurchaseOrderMst = new HashSet<Med_PurchaseOrderMst>();
            this.PurchaseOrderMsts = new HashSet<PurchaseOrderMst>();
        }
    
        public int BranchTypeCode { get; set; }
        public string BranchTypeName { get; set; }
        public string SubTypeName { get; set; }
        public Nullable<byte> SubTypeCode { get; set; }
        public Nullable<byte> SortID { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Med_PurchaseOrderMst> Med_PurchaseOrderMst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderMst> PurchaseOrderMsts { get; set; }
    }
}
