//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContainMst
    {
        public int ContainMstID { get; set; }
        public string ContainName { get; set; }
        public Nullable<byte> ScheduleCode { get; set; }
        public Nullable<bool> DPCO { get; set; }
    }
}
