//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterMst
    {
        public int CounterMstID { get; set; }
        public int CrId { get; set; }
        public string LogInName { get; set; }
        public string CrName { get; set; }
        public string CrPass { get; set; }
        public Nullable<int> BranchTypeCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<int> MBranchCode { get; set; }
        public Nullable<int> TableCode { get; set; }
        public string CrEdit { get; set; }
        public string CrDel { get; set; }
        public string PcIPAddress { get; set; }
        public Nullable<bool> PrintPreview { get; set; }
        public Nullable<int> SortID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Sflag { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<int> LogID { get; set; }
        public string PcID { get; set; }
        public Nullable<int> Ever { get; set; }
        public Nullable<int> CompanyCode { get; set; }
    }
}
