//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterReportDet
    {
        public int CounterReportDetID { get; set; }
        public int CrID { get; set; }
        public Nullable<int> ReportCode { get; set; }
        public Nullable<int> TestCode { get; set; }
    }
}
