//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterDet
    {
        public int CounterDetID { get; set; }
        public int CrId { get; set; }
        public int MainMenuMstID { get; set; }
        public int MenuMstID { get; set; }
    }
}
