//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLogMaster
    {
        public int Id { get; set; }
        public string ErrorInfo { get; set; }
        public string MethodName { get; set; }
        public string ErrorURL { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
