//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogInInfo
    {
        public int LogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<System.TimeSpan> STime { get; set; }
        public string PcID { get; set; }
        public Nullable<int> Ever { get; set; }
        public string PcIPAddress { get; set; }
        public string Pcname { get; set; }
    }
}
