//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainMenuMst
    {
        public int MainMenuSrNo { get; set; }
        public byte MainMenuMstID { get; set; }
        public string MainMenuName { get; set; }
        public Nullable<byte> Valid { get; set; }
    }
}
