//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_GOrderConfirmMst
    {
        public int Med_GOrderConfirmMstID { get; set; }
        public Nullable<int> Med_PurchaseOrderMstID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<int> POCode { get; set; }
        public Nullable<System.DateTime> Med_GOrderConfirmDate { get; set; }
        public Nullable<byte> Rec { get; set; }
        public string Sflag { get; set; }
        public Nullable<System.DateTime> Sdate { get; set; }
        public Nullable<int> LogID { get; set; }
        public string PcID { get; set; }
        public Nullable<int> Ever { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public string Type { get; set; }
    }
}
