//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_QuaterMst
    {
        public int QuaterCode { get; set; }
        public string QuaterName { get; set; }
        public Nullable<byte> FromMontth { get; set; }
        public Nullable<byte> ToMonth { get; set; }
        public Nullable<byte> FromDay { get; set; }
        public Nullable<byte> ToDay { get; set; }
        public string YearType { get; set; }
    }
}
