//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedPaymentMst
    {
        public int MedPaymentMstID { get; set; }
        public Nullable<System.DateTime> MedPaymentDate { get; set; }
        public string Type { get; set; }
        public string BranchCode { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<bool> ChkInv { get; set; }
        public Nullable<int> BillNo { get; set; }
        public Nullable<decimal> BillAmt { get; set; }
        public Nullable<decimal> PayAmt { get; set; }
        public Nullable<bool> ChkDis { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> NetAmt { get; set; }
        public string Sflag { get; set; }
        public Nullable<System.DateTime> Sdate { get; set; }
        public Nullable<int> LogID { get; set; }
        public string PcID { get; set; }
        public Nullable<int> Ever { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public Nullable<int> POSMstID { get; set; }
    }
}
