//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuMst
    {
        public int MenuSRNO { get; set; }
        public byte MenuMstID { get; set; }
        public string MenuName { get; set; }
        public Nullable<byte> MainMenuMstID { get; set; }
        public Nullable<byte> Valid { get; set; }
        public string FormName { get; set; }
        public byte[] MenuImage { get; set; }
        public Nullable<int> MainGroupMstID { get; set; }
        public Nullable<int> ImageSize { get; set; }
        public Nullable<int> SortID { get; set; }
        public string DashBoard { get; set; }
        public string Shortcut { get; set; }
    }
}
