//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MED_GENMEDEntities : DbContext
    {
        public MED_GENMEDEntities()
            : base("name=MED_GENMEDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdMst> AdMsts { get; set; }
        public virtual DbSet<AreaMst> AreaMsts { get; set; }
        public virtual DbSet<BatchMst> BatchMsts { get; set; }
        public virtual DbSet<BranchCategoryMst> BranchCategoryMsts { get; set; }
        public virtual DbSet<BranchMst> BranchMsts { get; set; }
        public virtual DbSet<BranchTypeMst> BranchTypeMsts { get; set; }
        public virtual DbSet<CityMst> CityMsts { get; set; }
        public virtual DbSet<ContainMst> ContainMsts { get; set; }
        public virtual DbSet<CounterDet> CounterDets { get; set; }
        public virtual DbSet<CounterMst> CounterMsts { get; set; }
        public virtual DbSet<CounterReportDet> CounterReportDets { get; set; }
        public virtual DbSet<DiseaseMst> DiseaseMsts { get; set; }
        public virtual DbSet<ErrorLogMaster> ErrorLogMasters { get; set; }
        public virtual DbSet<GenericGroupMst> GenericGroupMsts { get; set; }
        public virtual DbSet<GenericMst> GenericMsts { get; set; }
        public virtual DbSet<GodownMst> GodownMsts { get; set; }
        public virtual DbSet<ImgUploadMst> ImgUploadMsts { get; set; }
        public virtual DbSet<LanguageMessage> LanguageMessages { get; set; }
        public virtual DbSet<LogInInfo> LogInInfoes { get; set; }
        public virtual DbSet<MainGroupMst> MainGroupMsts { get; set; }
        public virtual DbSet<MainMenuMst> MainMenuMsts { get; set; }
        public virtual DbSet<MainProductMst> MainProductMsts { get; set; }
        public virtual DbSet<MarginMst> MarginMsts { get; set; }
        public virtual DbSet<Med_FinYearMst> Med_FinYearMst { get; set; }
        public virtual DbSet<Med_GOrderConfirmMst> Med_GOrderConfirmMst { get; set; }
        public virtual DbSet<Med_OfferMst> Med_OfferMst { get; set; }
        public virtual DbSet<Med_PurchaseOrderDet> Med_PurchaseOrderDet { get; set; }
        public virtual DbSet<Med_PurchaseOrderDet_1> Med_PurchaseOrderDet_1 { get; set; }
        public virtual DbSet<Med_PurchaseOrderMst> Med_PurchaseOrderMst { get; set; }
        public virtual DbSet<Med_PurchaseReturnDet> Med_PurchaseReturnDet { get; set; }
        public virtual DbSet<Med_PurchaseReturnDet_1> Med_PurchaseReturnDet_1 { get; set; }
        public virtual DbSet<Med_PurchaseReturnMst> Med_PurchaseReturnMst { get; set; }
        public virtual DbSet<Med_QuaterMst> Med_QuaterMst { get; set; }
        public virtual DbSet<MenuMst> MenuMsts { get; set; }
        public virtual DbSet<MfgCompanyMst> MfgCompanyMsts { get; set; }
        public virtual DbSet<MktCompanyMst> MktCompanyMsts { get; set; }
        public virtual DbSet<MSpeer_lsns> MSpeer_lsns { get; set; }
        public virtual DbSet<POSDet> POSDets { get; set; }
        public virtual DbSet<POSMst> POSMsts { get; set; }
        public virtual DbSet<POSRetDet> POSRetDets { get; set; }
        public virtual DbSet<RackMst> RackMsts { get; set; }
        public virtual DbSet<ReportMst> ReportMsts { get; set; }
        public virtual DbSet<ReportTypeMst> ReportTypeMsts { get; set; }
        public virtual DbSet<StateMst> StateMsts { get; set; }
        public virtual DbSet<Stock_Medical> Stock_Medical { get; set; }
        public virtual DbSet<Stockist_SaleInvoiceDet> Stockist_SaleInvoiceDet { get; set; }
        public virtual DbSet<Stockist_SaleInvoiceDet_1> Stockist_SaleInvoiceDet_1 { get; set; }
        public virtual DbSet<Stockist_SaleInvoiceMst> Stockist_SaleInvoiceMst { get; set; }
        public virtual DbSet<Stockist_SaleReturnDet> Stockist_SaleReturnDet { get; set; }
        public virtual DbSet<Stockist_SaleReturnDet_1> Stockist_SaleReturnDet_1 { get; set; }
        public virtual DbSet<Stockist_SaleReturnMst> Stockist_SaleReturnMst { get; set; }
        public virtual DbSet<StorageMst> StorageMsts { get; set; }
        public virtual DbSet<SubProductMst> SubProductMsts { get; set; }
        public virtual DbSet<TableMst> TableMsts { get; set; }
        public virtual DbSet<TabletTypeMst> TabletTypeMsts { get; set; }
        public virtual DbSet<TalukaMst> TalukaMsts { get; set; }
        public virtual DbSet<TaxMst> TaxMsts { get; set; }
        public virtual DbSet<TestMst> TestMsts { get; set; }
        public virtual DbSet<UnitMst> UnitMsts { get; set; }
        public virtual DbSet<Med_ExpenseMst> Med_ExpenseMst { get; set; }
        public virtual DbSet<Med_ExpGroupMst> Med_ExpGroupMst { get; set; }
        public virtual DbSet<Med_ExpMst> Med_ExpMst { get; set; }
        public virtual DbSet<MedPaymentMst> MedPaymentMsts { get; set; }
        public virtual DbSet<MSpeer_originatorid_history> MSpeer_originatorid_history { get; set; }
        public virtual DbSet<TmpGiftReportMst> TmpGiftReportMsts { get; set; }
        public virtual DbSet<ProductMst> ProductMsts { get; set; }
        public virtual DbSet<Stock_Genmed> Stock_Genmed { get; set; }
        public virtual DbSet<Stock_Stockist> Stock_Stockist { get; set; }
        public virtual DbSet<DivisionMst> DivisionMsts { get; set; }
        public virtual DbSet<SaleInvoiceDet> SaleInvoiceDets { get; set; }
        public virtual DbSet<SaleInvoiceDet_1> SaleInvoiceDet_1 { get; set; }
        public virtual DbSet<SaleInvoiceMst> SaleInvoiceMsts { get; set; }
        public virtual DbSet<SaleReturnDet> SaleReturnDets { get; set; }
        public virtual DbSet<SaleReturnDet_1> SaleReturnDet_1 { get; set; }
        public virtual DbSet<SaleReturnMst> SaleReturnMsts { get; set; }
        public virtual DbSet<ScheduleMst> ScheduleMsts { get; set; }
        public virtual DbSet<GOrderConfirmMst> GOrderConfirmMsts { get; set; }
    
        public virtual int ProductMst_bulkdelete(Nullable<long> sync_min_timestamp, Nullable<int> sync_scope_local_id)
        {
            var sync_min_timestampParameter = sync_min_timestamp.HasValue ?
                new ObjectParameter("sync_min_timestamp", sync_min_timestamp) :
                new ObjectParameter("sync_min_timestamp", typeof(long));
    
            var sync_scope_local_idParameter = sync_scope_local_id.HasValue ?
                new ObjectParameter("sync_scope_local_id", sync_scope_local_id) :
                new ObjectParameter("sync_scope_local_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductMst_bulkdelete", sync_min_timestampParameter, sync_scope_local_idParameter);
        }
    
        public virtual int ProductMst_bulkinsert(Nullable<long> sync_min_timestamp, Nullable<int> sync_scope_local_id)
        {
            var sync_min_timestampParameter = sync_min_timestamp.HasValue ?
                new ObjectParameter("sync_min_timestamp", sync_min_timestamp) :
                new ObjectParameter("sync_min_timestamp", typeof(long));
    
            var sync_scope_local_idParameter = sync_scope_local_id.HasValue ?
                new ObjectParameter("sync_scope_local_id", sync_scope_local_id) :
                new ObjectParameter("sync_scope_local_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductMst_bulkinsert", sync_min_timestampParameter, sync_scope_local_idParameter);
        }
    
        public virtual int ProductMst_bulkupdate(Nullable<long> sync_min_timestamp, Nullable<int> sync_scope_local_id)
        {
            var sync_min_timestampParameter = sync_min_timestamp.HasValue ?
                new ObjectParameter("sync_min_timestamp", sync_min_timestamp) :
                new ObjectParameter("sync_min_timestamp", typeof(long));
    
            var sync_scope_local_idParameter = sync_scope_local_id.HasValue ?
                new ObjectParameter("sync_scope_local_id", sync_scope_local_id) :
                new ObjectParameter("sync_scope_local_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductMst_bulkupdate", sync_min_timestampParameter, sync_scope_local_idParameter);
        }
    
        public virtual int ProductMst_delete(Nullable<int> p_1, Nullable<int> sync_force_write, Nullable<long> sync_min_timestamp, ObjectParameter sync_row_count)
        {
            var p_1Parameter = p_1.HasValue ?
                new ObjectParameter("P_1", p_1) :
                new ObjectParameter("P_1", typeof(int));
    
            var sync_force_writeParameter = sync_force_write.HasValue ?
                new ObjectParameter("sync_force_write", sync_force_write) :
                new ObjectParameter("sync_force_write", typeof(int));
    
            var sync_min_timestampParameter = sync_min_timestamp.HasValue ?
                new ObjectParameter("sync_min_timestamp", sync_min_timestamp) :
                new ObjectParameter("sync_min_timestamp", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductMst_delete", p_1Parameter, sync_force_writeParameter, sync_min_timestampParameter, sync_row_count);
        }
    
        public virtual int ProductMst_deletemetadata(Nullable<int> p_1, Nullable<int> sync_check_concurrency, Nullable<long> sync_row_timestamp, ObjectParameter sync_row_count)
        {
            var p_1Parameter = p_1.HasValue ?
                new ObjectParameter("P_1", p_1) :
                new ObjectParameter("P_1", typeof(int));
    
            var sync_check_concurrencyParameter = sync_check_concurrency.HasValue ?
                new ObjectParameter("sync_check_concurrency", sync_check_concurrency) :
                new ObjectParameter("sync_check_concurrency", typeof(int));
    
            var sync_row_timestampParameter = sync_row_timestamp.HasValue ?
                new ObjectParameter("sync_row_timestamp", sync_row_timestamp) :
                new ObjectParameter("sync_row_timestamp", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductMst_deletemetadata", p_1Parameter, sync_check_concurrencyParameter, sync_row_timestampParameter, sync_row_count);
        }
    
        public virtual int ProductMst_insert(Nullable<int> p_1, string p_2, Nullable<int> p_3, ObjectParameter sync_row_count)
        {
            var p_1Parameter = p_1.HasValue ?
                new ObjectParameter("P_1", p_1) :
                new ObjectParameter("P_1", typeof(int));
    
            var p_2Parameter = p_2 != null ?
                new ObjectParameter("P_2", p_2) :
                new ObjectParameter("P_2", typeof(string));
    
            var p_3Parameter = p_3.HasValue ?
                new ObjectParameter("P_3", p_3) :
                new ObjectParameter("P_3", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductMst_insert", p_1Parameter, p_2Parameter, p_3Parameter, sync_row_count);
        }
    
        public virtual int ProductMst_insertmetadata(Nullable<int> p_1, Nullable<int> sync_scope_local_id, Nullable<int> sync_row_is_tombstone, Nullable<int> sync_create_peer_key, Nullable<long> sync_create_peer_timestamp, Nullable<int> sync_update_peer_key, Nullable<long> sync_update_peer_timestamp, Nullable<int> sync_check_concurrency, Nullable<long> sync_row_timestamp, ObjectParameter sync_row_count)
        {
            var p_1Parameter = p_1.HasValue ?
                new ObjectParameter("P_1", p_1) :
                new ObjectParameter("P_1", typeof(int));
    
            var sync_scope_local_idParameter = sync_scope_local_id.HasValue ?
                new ObjectParameter("sync_scope_local_id", sync_scope_local_id) :
                new ObjectParameter("sync_scope_local_id", typeof(int));
    
            var sync_row_is_tombstoneParameter = sync_row_is_tombstone.HasValue ?
                new ObjectParameter("sync_row_is_tombstone", sync_row_is_tombstone) :
                new ObjectParameter("sync_row_is_tombstone", typeof(int));
    
            var sync_create_peer_keyParameter = sync_create_peer_key.HasValue ?
                new ObjectParameter("sync_create_peer_key", sync_create_peer_key) :
                new ObjectParameter("sync_create_peer_key", typeof(int));
    
            var sync_create_peer_timestampParameter = sync_create_peer_timestamp.HasValue ?
                new ObjectParameter("sync_create_peer_timestamp", sync_create_peer_timestamp) :
                new ObjectParameter("sync_create_peer_timestamp", typeof(long));
    
            var sync_update_peer_keyParameter = sync_update_peer_key.HasValue ?
                new ObjectParameter("sync_update_peer_key", sync_update_peer_key) :
                new ObjectParameter("sync_update_peer_key", typeof(int));
    
            var sync_update_peer_timestampParameter = sync_update_peer_timestamp.HasValue ?
                new ObjectParameter("sync_update_peer_timestamp", sync_update_peer_timestamp) :
                new ObjectParameter("sync_update_peer_timestamp", typeof(long));
    
            var sync_check_concurrencyParameter = sync_check_concurrency.HasValue ?
                new ObjectParameter("sync_check_concurrency", sync_check_concurrency) :
                new ObjectParameter("sync_check_concurrency", typeof(int));
    
            var sync_row_timestampParameter = sync_row_timestamp.HasValue ?
                new ObjectParameter("sync_row_timestamp", sync_row_timestamp) :
                new ObjectParameter("sync_row_timestamp", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductMst_insertmetadata", p_1Parameter, sync_scope_local_idParameter, sync_row_is_tombstoneParameter, sync_create_peer_keyParameter, sync_create_peer_timestampParameter, sync_update_peer_keyParameter, sync_update_peer_timestampParameter, sync_check_concurrencyParameter, sync_row_timestampParameter, sync_row_count);
        }
    
        public virtual int ProductMst_selectchanges(Nullable<long> sync_min_timestamp, Nullable<int> sync_scope_local_id, Nullable<int> sync_scope_restore_count, Nullable<int> sync_update_peer_key)
        {
            var sync_min_timestampParameter = sync_min_timestamp.HasValue ?
                new ObjectParameter("sync_min_timestamp", sync_min_timestamp) :
                new ObjectParameter("sync_min_timestamp", typeof(long));
    
            var sync_scope_local_idParameter = sync_scope_local_id.HasValue ?
                new ObjectParameter("sync_scope_local_id", sync_scope_local_id) :
                new ObjectParameter("sync_scope_local_id", typeof(int));
    
            var sync_scope_restore_countParameter = sync_scope_restore_count.HasValue ?
                new ObjectParameter("sync_scope_restore_count", sync_scope_restore_count) :
                new ObjectParameter("sync_scope_restore_count", typeof(int));
    
            var sync_update_peer_keyParameter = sync_update_peer_key.HasValue ?
                new ObjectParameter("sync_update_peer_key", sync_update_peer_key) :
                new ObjectParameter("sync_update_peer_key", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductMst_selectchanges", sync_min_timestampParameter, sync_scope_local_idParameter, sync_scope_restore_countParameter, sync_update_peer_keyParameter);
        }
    
        public virtual int ProductMst_selectrow(Nullable<int> p_1, Nullable<int> sync_scope_local_id, Nullable<int> sync_scope_restore_count)
        {
            var p_1Parameter = p_1.HasValue ?
                new ObjectParameter("P_1", p_1) :
                new ObjectParameter("P_1", typeof(int));
    
            var sync_scope_local_idParameter = sync_scope_local_id.HasValue ?
                new ObjectParameter("sync_scope_local_id", sync_scope_local_id) :
                new ObjectParameter("sync_scope_local_id", typeof(int));
    
            var sync_scope_restore_countParameter = sync_scope_restore_count.HasValue ?
                new ObjectParameter("sync_scope_restore_count", sync_scope_restore_count) :
                new ObjectParameter("sync_scope_restore_count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductMst_selectrow", p_1Parameter, sync_scope_local_idParameter, sync_scope_restore_countParameter);
        }
    
        public virtual int ProductMst_update(Nullable<int> p_1, string p_2, Nullable<int> p_3, Nullable<int> sync_force_write, Nullable<long> sync_min_timestamp, ObjectParameter sync_row_count)
        {
            var p_1Parameter = p_1.HasValue ?
                new ObjectParameter("P_1", p_1) :
                new ObjectParameter("P_1", typeof(int));
    
            var p_2Parameter = p_2 != null ?
                new ObjectParameter("P_2", p_2) :
                new ObjectParameter("P_2", typeof(string));
    
            var p_3Parameter = p_3.HasValue ?
                new ObjectParameter("P_3", p_3) :
                new ObjectParameter("P_3", typeof(int));
    
            var sync_force_writeParameter = sync_force_write.HasValue ?
                new ObjectParameter("sync_force_write", sync_force_write) :
                new ObjectParameter("sync_force_write", typeof(int));
    
            var sync_min_timestampParameter = sync_min_timestamp.HasValue ?
                new ObjectParameter("sync_min_timestamp", sync_min_timestamp) :
                new ObjectParameter("sync_min_timestamp", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductMst_update", p_1Parameter, p_2Parameter, p_3Parameter, sync_force_writeParameter, sync_min_timestampParameter, sync_row_count);
        }
    
        public virtual int ProductMst_updatemetadata(Nullable<int> p_1, Nullable<int> sync_scope_local_id, Nullable<int> sync_row_is_tombstone, Nullable<int> sync_create_peer_key, Nullable<long> sync_create_peer_timestamp, Nullable<int> sync_update_peer_key, Nullable<long> sync_update_peer_timestamp, Nullable<int> sync_check_concurrency, Nullable<long> sync_row_timestamp, ObjectParameter sync_row_count)
        {
            var p_1Parameter = p_1.HasValue ?
                new ObjectParameter("P_1", p_1) :
                new ObjectParameter("P_1", typeof(int));
    
            var sync_scope_local_idParameter = sync_scope_local_id.HasValue ?
                new ObjectParameter("sync_scope_local_id", sync_scope_local_id) :
                new ObjectParameter("sync_scope_local_id", typeof(int));
    
            var sync_row_is_tombstoneParameter = sync_row_is_tombstone.HasValue ?
                new ObjectParameter("sync_row_is_tombstone", sync_row_is_tombstone) :
                new ObjectParameter("sync_row_is_tombstone", typeof(int));
    
            var sync_create_peer_keyParameter = sync_create_peer_key.HasValue ?
                new ObjectParameter("sync_create_peer_key", sync_create_peer_key) :
                new ObjectParameter("sync_create_peer_key", typeof(int));
    
            var sync_create_peer_timestampParameter = sync_create_peer_timestamp.HasValue ?
                new ObjectParameter("sync_create_peer_timestamp", sync_create_peer_timestamp) :
                new ObjectParameter("sync_create_peer_timestamp", typeof(long));
    
            var sync_update_peer_keyParameter = sync_update_peer_key.HasValue ?
                new ObjectParameter("sync_update_peer_key", sync_update_peer_key) :
                new ObjectParameter("sync_update_peer_key", typeof(int));
    
            var sync_update_peer_timestampParameter = sync_update_peer_timestamp.HasValue ?
                new ObjectParameter("sync_update_peer_timestamp", sync_update_peer_timestamp) :
                new ObjectParameter("sync_update_peer_timestamp", typeof(long));
    
            var sync_check_concurrencyParameter = sync_check_concurrency.HasValue ?
                new ObjectParameter("sync_check_concurrency", sync_check_concurrency) :
                new ObjectParameter("sync_check_concurrency", typeof(int));
    
            var sync_row_timestampParameter = sync_row_timestamp.HasValue ?
                new ObjectParameter("sync_row_timestamp", sync_row_timestamp) :
                new ObjectParameter("sync_row_timestamp", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductMst_updatemetadata", p_1Parameter, sync_scope_local_idParameter, sync_row_is_tombstoneParameter, sync_create_peer_keyParameter, sync_create_peer_timestampParameter, sync_update_peer_keyParameter, sync_update_peer_timestampParameter, sync_check_concurrencyParameter, sync_row_timestampParameter, sync_row_count);
        }
    
        public virtual int sp_MSdel_dboDoctorMst_msrepl_ccs(Nullable<byte> pkc1)
        {
            var pkc1Parameter = pkc1.HasValue ?
                new ObjectParameter("pkc1", pkc1) :
                new ObjectParameter("pkc1", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSdel_dboDoctorMst_msrepl_ccs", pkc1Parameter);
        }
    
        public virtual int sp_MSdel_dboMed_GOrderConfirmMst_msrepl_ccs(Nullable<int> pkc1)
        {
            var pkc1Parameter = pkc1.HasValue ?
                new ObjectParameter("pkc1", pkc1) :
                new ObjectParameter("pkc1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSdel_dboMed_GOrderConfirmMst_msrepl_ccs", pkc1Parameter);
        }
    
        public virtual int sp_MSdel_dboMed_PurchaseOrderDet_1_msrepl_ccs(Nullable<int> pkc1)
        {
            var pkc1Parameter = pkc1.HasValue ?
                new ObjectParameter("pkc1", pkc1) :
                new ObjectParameter("pkc1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSdel_dboMed_PurchaseOrderDet_1_msrepl_ccs", pkc1Parameter);
        }
    
        public virtual int sp_MSdel_dboMed_PurchaseOrderDet_msrepl_ccs(Nullable<int> pkc1)
        {
            var pkc1Parameter = pkc1.HasValue ?
                new ObjectParameter("pkc1", pkc1) :
                new ObjectParameter("pkc1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSdel_dboMed_PurchaseOrderDet_msrepl_ccs", pkc1Parameter);
        }
    
        public virtual int sp_MSdel_dboMed_PurchaseOrderMst_msrepl_ccs(Nullable<int> pkc1)
        {
            var pkc1Parameter = pkc1.HasValue ?
                new ObjectParameter("pkc1", pkc1) :
                new ObjectParameter("pkc1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSdel_dboMed_PurchaseOrderMst_msrepl_ccs", pkc1Parameter);
        }
    
        public virtual int sp_MSdel_dboPatientMst_msrepl_ccs(Nullable<byte> pkc1)
        {
            var pkc1Parameter = pkc1.HasValue ?
                new ObjectParameter("pkc1", pkc1) :
                new ObjectParameter("pkc1", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSdel_dboPatientMst_msrepl_ccs", pkc1Parameter);
        }
    
        public virtual int sp_MSdel_dboPOSDet_msrepl_ccs(Nullable<int> pkc1)
        {
            var pkc1Parameter = pkc1.HasValue ?
                new ObjectParameter("pkc1", pkc1) :
                new ObjectParameter("pkc1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSdel_dboPOSDet_msrepl_ccs", pkc1Parameter);
        }
    
        public virtual int sp_MSdel_dboPOSMst_msrepl_ccs(Nullable<int> pkc1)
        {
            var pkc1Parameter = pkc1.HasValue ?
                new ObjectParameter("pkc1", pkc1) :
                new ObjectParameter("pkc1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSdel_dboPOSMst_msrepl_ccs", pkc1Parameter);
        }
    
        public virtual int sp_MSdel_dboPOSRetDet_msrepl_ccs(Nullable<int> pkc1)
        {
            var pkc1Parameter = pkc1.HasValue ?
                new ObjectParameter("pkc1", pkc1) :
                new ObjectParameter("pkc1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSdel_dboPOSRetDet_msrepl_ccs", pkc1Parameter);
        }
    
        public virtual int sp_MSdel_dboPOSRetMst_msrepl_ccs(Nullable<int> pkc1)
        {
            var pkc1Parameter = pkc1.HasValue ?
                new ObjectParameter("pkc1", pkc1) :
                new ObjectParameter("pkc1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSdel_dboPOSRetMst_msrepl_ccs", pkc1Parameter);
        }
    
        public virtual int sp_MSdel_dboStock_Medical_msrepl_ccs(Nullable<int> pkc1)
        {
            var pkc1Parameter = pkc1.HasValue ?
                new ObjectParameter("pkc1", pkc1) :
                new ObjectParameter("pkc1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSdel_dboStock_Medical_msrepl_ccs", pkc1Parameter);
        }
    
        public virtual int sp_MSdel_dboStockist_SaleInvoiceDet_1_msrepl_ccs(Nullable<int> pkc1)
        {
            var pkc1Parameter = pkc1.HasValue ?
                new ObjectParameter("pkc1", pkc1) :
                new ObjectParameter("pkc1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSdel_dboStockist_SaleInvoiceDet_1_msrepl_ccs", pkc1Parameter);
        }
    
        public virtual int sp_MSdel_dboStockist_SaleInvoiceDet_msrepl_ccs(Nullable<int> pkc1)
        {
            var pkc1Parameter = pkc1.HasValue ?
                new ObjectParameter("pkc1", pkc1) :
                new ObjectParameter("pkc1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSdel_dboStockist_SaleInvoiceDet_msrepl_ccs", pkc1Parameter);
        }
    
        public virtual int sp_MSdel_dboStockist_SaleInvoiceMst_msrepl_ccs(Nullable<int> pkc1)
        {
            var pkc1Parameter = pkc1.HasValue ?
                new ObjectParameter("pkc1", pkc1) :
                new ObjectParameter("pkc1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSdel_dboStockist_SaleInvoiceMst_msrepl_ccs", pkc1Parameter);
        }
    
        public virtual int sp_MSins_dboDoctorMst_msrepl_ccs(Nullable<byte> c1, Nullable<byte> c2, string c3, string c4, string c5, string c6, Nullable<int> c7, Nullable<int> c8, Nullable<System.DateTime> c9)
        {
            var c1Parameter = c1.HasValue ?
                new ObjectParameter("c1", c1) :
                new ObjectParameter("c1", typeof(byte));
    
            var c2Parameter = c2.HasValue ?
                new ObjectParameter("c2", c2) :
                new ObjectParameter("c2", typeof(byte));
    
            var c3Parameter = c3 != null ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(string));
    
            var c4Parameter = c4 != null ?
                new ObjectParameter("c4", c4) :
                new ObjectParameter("c4", typeof(string));
    
            var c5Parameter = c5 != null ?
                new ObjectParameter("c5", c5) :
                new ObjectParameter("c5", typeof(string));
    
            var c6Parameter = c6 != null ?
                new ObjectParameter("c6", c6) :
                new ObjectParameter("c6", typeof(string));
    
            var c7Parameter = c7.HasValue ?
                new ObjectParameter("c7", c7) :
                new ObjectParameter("c7", typeof(int));
    
            var c8Parameter = c8.HasValue ?
                new ObjectParameter("c8", c8) :
                new ObjectParameter("c8", typeof(int));
    
            var c9Parameter = c9.HasValue ?
                new ObjectParameter("c9", c9) :
                new ObjectParameter("c9", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSins_dboDoctorMst_msrepl_ccs", c1Parameter, c2Parameter, c3Parameter, c4Parameter, c5Parameter, c6Parameter, c7Parameter, c8Parameter, c9Parameter);
        }
    
        public virtual int sp_MSins_dboMed_GOrderConfirmMst_msrepl_ccs(Nullable<int> c1, Nullable<int> c2, Nullable<int> c3, Nullable<int> c4, Nullable<System.DateTime> c5, Nullable<byte> c6, string c7, Nullable<System.DateTime> c8, Nullable<int> c9, string c10, Nullable<int> c11, Nullable<int> c12)
        {
            var c1Parameter = c1.HasValue ?
                new ObjectParameter("c1", c1) :
                new ObjectParameter("c1", typeof(int));
    
            var c2Parameter = c2.HasValue ?
                new ObjectParameter("c2", c2) :
                new ObjectParameter("c2", typeof(int));
    
            var c3Parameter = c3.HasValue ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(int));
    
            var c4Parameter = c4.HasValue ?
                new ObjectParameter("c4", c4) :
                new ObjectParameter("c4", typeof(int));
    
            var c5Parameter = c5.HasValue ?
                new ObjectParameter("c5", c5) :
                new ObjectParameter("c5", typeof(System.DateTime));
    
            var c6Parameter = c6.HasValue ?
                new ObjectParameter("c6", c6) :
                new ObjectParameter("c6", typeof(byte));
    
            var c7Parameter = c7 != null ?
                new ObjectParameter("c7", c7) :
                new ObjectParameter("c7", typeof(string));
    
            var c8Parameter = c8.HasValue ?
                new ObjectParameter("c8", c8) :
                new ObjectParameter("c8", typeof(System.DateTime));
    
            var c9Parameter = c9.HasValue ?
                new ObjectParameter("c9", c9) :
                new ObjectParameter("c9", typeof(int));
    
            var c10Parameter = c10 != null ?
                new ObjectParameter("c10", c10) :
                new ObjectParameter("c10", typeof(string));
    
            var c11Parameter = c11.HasValue ?
                new ObjectParameter("c11", c11) :
                new ObjectParameter("c11", typeof(int));
    
            var c12Parameter = c12.HasValue ?
                new ObjectParameter("c12", c12) :
                new ObjectParameter("c12", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSins_dboMed_GOrderConfirmMst_msrepl_ccs", c1Parameter, c2Parameter, c3Parameter, c4Parameter, c5Parameter, c6Parameter, c7Parameter, c8Parameter, c9Parameter, c10Parameter, c11Parameter, c12Parameter);
        }
    
        public virtual int sp_MSins_dboMed_PurchaseOrderDet_1_msrepl_ccs(Nullable<int> c1, Nullable<int> c2, Nullable<byte> c3, string c4, Nullable<decimal> c5)
        {
            var c1Parameter = c1.HasValue ?
                new ObjectParameter("c1", c1) :
                new ObjectParameter("c1", typeof(int));
    
            var c2Parameter = c2.HasValue ?
                new ObjectParameter("c2", c2) :
                new ObjectParameter("c2", typeof(int));
    
            var c3Parameter = c3.HasValue ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(byte));
    
            var c4Parameter = c4 != null ?
                new ObjectParameter("c4", c4) :
                new ObjectParameter("c4", typeof(string));
    
            var c5Parameter = c5.HasValue ?
                new ObjectParameter("c5", c5) :
                new ObjectParameter("c5", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSins_dboMed_PurchaseOrderDet_1_msrepl_ccs", c1Parameter, c2Parameter, c3Parameter, c4Parameter, c5Parameter);
        }
    
        public virtual int sp_MSins_dboMed_PurchaseOrderDet_msrepl_ccs(Nullable<int> c1, Nullable<int> c2, Nullable<int> c3, Nullable<int> c4, Nullable<decimal> c5, Nullable<decimal> c6, Nullable<decimal> c7, Nullable<decimal> c8, Nullable<int> c9)
        {
            var c1Parameter = c1.HasValue ?
                new ObjectParameter("c1", c1) :
                new ObjectParameter("c1", typeof(int));
    
            var c2Parameter = c2.HasValue ?
                new ObjectParameter("c2", c2) :
                new ObjectParameter("c2", typeof(int));
    
            var c3Parameter = c3.HasValue ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(int));
    
            var c4Parameter = c4.HasValue ?
                new ObjectParameter("c4", c4) :
                new ObjectParameter("c4", typeof(int));
    
            var c5Parameter = c5.HasValue ?
                new ObjectParameter("c5", c5) :
                new ObjectParameter("c5", typeof(decimal));
    
            var c6Parameter = c6.HasValue ?
                new ObjectParameter("c6", c6) :
                new ObjectParameter("c6", typeof(decimal));
    
            var c7Parameter = c7.HasValue ?
                new ObjectParameter("c7", c7) :
                new ObjectParameter("c7", typeof(decimal));
    
            var c8Parameter = c8.HasValue ?
                new ObjectParameter("c8", c8) :
                new ObjectParameter("c8", typeof(decimal));
    
            var c9Parameter = c9.HasValue ?
                new ObjectParameter("c9", c9) :
                new ObjectParameter("c9", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSins_dboMed_PurchaseOrderDet_msrepl_ccs", c1Parameter, c2Parameter, c3Parameter, c4Parameter, c5Parameter, c6Parameter, c7Parameter, c8Parameter, c9Parameter);
        }
    
        public virtual int sp_MSins_dboMed_PurchaseOrderMst_msrepl_ccs(Nullable<int> c1, Nullable<int> c2, Nullable<System.DateTime> c3, Nullable<int> c4, Nullable<int> c5, Nullable<byte> c6, string c7, Nullable<System.DateTime> c8, Nullable<int> c9, string c10, Nullable<int> c11, Nullable<int> c12, Nullable<bool> c13)
        {
            var c1Parameter = c1.HasValue ?
                new ObjectParameter("c1", c1) :
                new ObjectParameter("c1", typeof(int));
    
            var c2Parameter = c2.HasValue ?
                new ObjectParameter("c2", c2) :
                new ObjectParameter("c2", typeof(int));
    
            var c3Parameter = c3.HasValue ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(System.DateTime));
    
            var c4Parameter = c4.HasValue ?
                new ObjectParameter("c4", c4) :
                new ObjectParameter("c4", typeof(int));
    
            var c5Parameter = c5.HasValue ?
                new ObjectParameter("c5", c5) :
                new ObjectParameter("c5", typeof(int));
    
            var c6Parameter = c6.HasValue ?
                new ObjectParameter("c6", c6) :
                new ObjectParameter("c6", typeof(byte));
    
            var c7Parameter = c7 != null ?
                new ObjectParameter("c7", c7) :
                new ObjectParameter("c7", typeof(string));
    
            var c8Parameter = c8.HasValue ?
                new ObjectParameter("c8", c8) :
                new ObjectParameter("c8", typeof(System.DateTime));
    
            var c9Parameter = c9.HasValue ?
                new ObjectParameter("c9", c9) :
                new ObjectParameter("c9", typeof(int));
    
            var c10Parameter = c10 != null ?
                new ObjectParameter("c10", c10) :
                new ObjectParameter("c10", typeof(string));
    
            var c11Parameter = c11.HasValue ?
                new ObjectParameter("c11", c11) :
                new ObjectParameter("c11", typeof(int));
    
            var c12Parameter = c12.HasValue ?
                new ObjectParameter("c12", c12) :
                new ObjectParameter("c12", typeof(int));
    
            var c13Parameter = c13.HasValue ?
                new ObjectParameter("c13", c13) :
                new ObjectParameter("c13", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSins_dboMed_PurchaseOrderMst_msrepl_ccs", c1Parameter, c2Parameter, c3Parameter, c4Parameter, c5Parameter, c6Parameter, c7Parameter, c8Parameter, c9Parameter, c10Parameter, c11Parameter, c12Parameter, c13Parameter);
        }
    
        public virtual int sp_MSins_dboPatientMst_msrepl_ccs(Nullable<byte> c1, Nullable<byte> c2, string c3, string c4, string c5, Nullable<int> c6, Nullable<int> c7, Nullable<System.DateTime> c8)
        {
            var c1Parameter = c1.HasValue ?
                new ObjectParameter("c1", c1) :
                new ObjectParameter("c1", typeof(byte));
    
            var c2Parameter = c2.HasValue ?
                new ObjectParameter("c2", c2) :
                new ObjectParameter("c2", typeof(byte));
    
            var c3Parameter = c3 != null ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(string));
    
            var c4Parameter = c4 != null ?
                new ObjectParameter("c4", c4) :
                new ObjectParameter("c4", typeof(string));
    
            var c5Parameter = c5 != null ?
                new ObjectParameter("c5", c5) :
                new ObjectParameter("c5", typeof(string));
    
            var c6Parameter = c6.HasValue ?
                new ObjectParameter("c6", c6) :
                new ObjectParameter("c6", typeof(int));
    
            var c7Parameter = c7.HasValue ?
                new ObjectParameter("c7", c7) :
                new ObjectParameter("c7", typeof(int));
    
            var c8Parameter = c8.HasValue ?
                new ObjectParameter("c8", c8) :
                new ObjectParameter("c8", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSins_dboPatientMst_msrepl_ccs", c1Parameter, c2Parameter, c3Parameter, c4Parameter, c5Parameter, c6Parameter, c7Parameter, c8Parameter);
        }
    
        public virtual int sp_MSins_dboPOSDet_msrepl_ccs(Nullable<int> c1, Nullable<int> c2, Nullable<byte> c3, Nullable<int> c4, Nullable<int> c5, string c6, string c7, string c8, Nullable<decimal> c9, Nullable<decimal> c10, Nullable<decimal> c11, Nullable<decimal> c12, Nullable<decimal> c13, Nullable<decimal> c14, Nullable<decimal> c15, Nullable<decimal> c16, Nullable<decimal> c17, Nullable<byte> c18, Nullable<decimal> c19, Nullable<decimal> c20, Nullable<decimal> c21, Nullable<decimal> c22, Nullable<decimal> c23, Nullable<decimal> c24, Nullable<bool> c25, Nullable<decimal> c26, Nullable<int> c27, Nullable<bool> c28)
        {
            var c1Parameter = c1.HasValue ?
                new ObjectParameter("c1", c1) :
                new ObjectParameter("c1", typeof(int));
    
            var c2Parameter = c2.HasValue ?
                new ObjectParameter("c2", c2) :
                new ObjectParameter("c2", typeof(int));
    
            var c3Parameter = c3.HasValue ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(byte));
    
            var c4Parameter = c4.HasValue ?
                new ObjectParameter("c4", c4) :
                new ObjectParameter("c4", typeof(int));
    
            var c5Parameter = c5.HasValue ?
                new ObjectParameter("c5", c5) :
                new ObjectParameter("c5", typeof(int));
    
            var c6Parameter = c6 != null ?
                new ObjectParameter("c6", c6) :
                new ObjectParameter("c6", typeof(string));
    
            var c7Parameter = c7 != null ?
                new ObjectParameter("c7", c7) :
                new ObjectParameter("c7", typeof(string));
    
            var c8Parameter = c8 != null ?
                new ObjectParameter("c8", c8) :
                new ObjectParameter("c8", typeof(string));
    
            var c9Parameter = c9.HasValue ?
                new ObjectParameter("c9", c9) :
                new ObjectParameter("c9", typeof(decimal));
    
            var c10Parameter = c10.HasValue ?
                new ObjectParameter("c10", c10) :
                new ObjectParameter("c10", typeof(decimal));
    
            var c11Parameter = c11.HasValue ?
                new ObjectParameter("c11", c11) :
                new ObjectParameter("c11", typeof(decimal));
    
            var c12Parameter = c12.HasValue ?
                new ObjectParameter("c12", c12) :
                new ObjectParameter("c12", typeof(decimal));
    
            var c13Parameter = c13.HasValue ?
                new ObjectParameter("c13", c13) :
                new ObjectParameter("c13", typeof(decimal));
    
            var c14Parameter = c14.HasValue ?
                new ObjectParameter("c14", c14) :
                new ObjectParameter("c14", typeof(decimal));
    
            var c15Parameter = c15.HasValue ?
                new ObjectParameter("c15", c15) :
                new ObjectParameter("c15", typeof(decimal));
    
            var c16Parameter = c16.HasValue ?
                new ObjectParameter("c16", c16) :
                new ObjectParameter("c16", typeof(decimal));
    
            var c17Parameter = c17.HasValue ?
                new ObjectParameter("c17", c17) :
                new ObjectParameter("c17", typeof(decimal));
    
            var c18Parameter = c18.HasValue ?
                new ObjectParameter("c18", c18) :
                new ObjectParameter("c18", typeof(byte));
    
            var c19Parameter = c19.HasValue ?
                new ObjectParameter("c19", c19) :
                new ObjectParameter("c19", typeof(decimal));
    
            var c20Parameter = c20.HasValue ?
                new ObjectParameter("c20", c20) :
                new ObjectParameter("c20", typeof(decimal));
    
            var c21Parameter = c21.HasValue ?
                new ObjectParameter("c21", c21) :
                new ObjectParameter("c21", typeof(decimal));
    
            var c22Parameter = c22.HasValue ?
                new ObjectParameter("c22", c22) :
                new ObjectParameter("c22", typeof(decimal));
    
            var c23Parameter = c23.HasValue ?
                new ObjectParameter("c23", c23) :
                new ObjectParameter("c23", typeof(decimal));
    
            var c24Parameter = c24.HasValue ?
                new ObjectParameter("c24", c24) :
                new ObjectParameter("c24", typeof(decimal));
    
            var c25Parameter = c25.HasValue ?
                new ObjectParameter("c25", c25) :
                new ObjectParameter("c25", typeof(bool));
    
            var c26Parameter = c26.HasValue ?
                new ObjectParameter("c26", c26) :
                new ObjectParameter("c26", typeof(decimal));
    
            var c27Parameter = c27.HasValue ?
                new ObjectParameter("c27", c27) :
                new ObjectParameter("c27", typeof(int));
    
            var c28Parameter = c28.HasValue ?
                new ObjectParameter("c28", c28) :
                new ObjectParameter("c28", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSins_dboPOSDet_msrepl_ccs", c1Parameter, c2Parameter, c3Parameter, c4Parameter, c5Parameter, c6Parameter, c7Parameter, c8Parameter, c9Parameter, c10Parameter, c11Parameter, c12Parameter, c13Parameter, c14Parameter, c15Parameter, c16Parameter, c17Parameter, c18Parameter, c19Parameter, c20Parameter, c21Parameter, c22Parameter, c23Parameter, c24Parameter, c25Parameter, c26Parameter, c27Parameter, c28Parameter);
        }
    
        public virtual int sp_MSins_dboPOSMst_msrepl_ccs(Nullable<int> c1, Nullable<int> c2, Nullable<int> c3, Nullable<System.DateTime> c4, Nullable<byte> c5, Nullable<byte> c6, Nullable<int> c7, Nullable<byte> c8, string c9, Nullable<System.DateTime> c10, Nullable<int> c11, string c12, Nullable<int> c13, Nullable<int> c14, string c15)
        {
            var c1Parameter = c1.HasValue ?
                new ObjectParameter("c1", c1) :
                new ObjectParameter("c1", typeof(int));
    
            var c2Parameter = c2.HasValue ?
                new ObjectParameter("c2", c2) :
                new ObjectParameter("c2", typeof(int));
    
            var c3Parameter = c3.HasValue ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(int));
    
            var c4Parameter = c4.HasValue ?
                new ObjectParameter("c4", c4) :
                new ObjectParameter("c4", typeof(System.DateTime));
    
            var c5Parameter = c5.HasValue ?
                new ObjectParameter("c5", c5) :
                new ObjectParameter("c5", typeof(byte));
    
            var c6Parameter = c6.HasValue ?
                new ObjectParameter("c6", c6) :
                new ObjectParameter("c6", typeof(byte));
    
            var c7Parameter = c7.HasValue ?
                new ObjectParameter("c7", c7) :
                new ObjectParameter("c7", typeof(int));
    
            var c8Parameter = c8.HasValue ?
                new ObjectParameter("c8", c8) :
                new ObjectParameter("c8", typeof(byte));
    
            var c9Parameter = c9 != null ?
                new ObjectParameter("c9", c9) :
                new ObjectParameter("c9", typeof(string));
    
            var c10Parameter = c10.HasValue ?
                new ObjectParameter("c10", c10) :
                new ObjectParameter("c10", typeof(System.DateTime));
    
            var c11Parameter = c11.HasValue ?
                new ObjectParameter("c11", c11) :
                new ObjectParameter("c11", typeof(int));
    
            var c12Parameter = c12 != null ?
                new ObjectParameter("c12", c12) :
                new ObjectParameter("c12", typeof(string));
    
            var c13Parameter = c13.HasValue ?
                new ObjectParameter("c13", c13) :
                new ObjectParameter("c13", typeof(int));
    
            var c14Parameter = c14.HasValue ?
                new ObjectParameter("c14", c14) :
                new ObjectParameter("c14", typeof(int));
    
            var c15Parameter = c15 != null ?
                new ObjectParameter("c15", c15) :
                new ObjectParameter("c15", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSins_dboPOSMst_msrepl_ccs", c1Parameter, c2Parameter, c3Parameter, c4Parameter, c5Parameter, c6Parameter, c7Parameter, c8Parameter, c9Parameter, c10Parameter, c11Parameter, c12Parameter, c13Parameter, c14Parameter, c15Parameter);
        }
    
        public virtual int sp_MSins_dboPOSRetDet_msrepl_ccs(Nullable<int> c1, Nullable<int> c2, Nullable<int> c3, Nullable<byte> c4, Nullable<int> c5, Nullable<int> c6, string c7, string c8, string c9, Nullable<decimal> c10, Nullable<decimal> c11, Nullable<decimal> c12, Nullable<decimal> c13, Nullable<decimal> c14, Nullable<decimal> c15, Nullable<decimal> c16, Nullable<decimal> c17, Nullable<decimal> c18, Nullable<byte> c19, Nullable<decimal> c20, Nullable<decimal> c21, Nullable<decimal> c22, Nullable<decimal> c23, Nullable<decimal> c24, Nullable<decimal> c25, Nullable<bool> c26, Nullable<decimal> c27, Nullable<int> c28)
        {
            var c1Parameter = c1.HasValue ?
                new ObjectParameter("c1", c1) :
                new ObjectParameter("c1", typeof(int));
    
            var c2Parameter = c2.HasValue ?
                new ObjectParameter("c2", c2) :
                new ObjectParameter("c2", typeof(int));
    
            var c3Parameter = c3.HasValue ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(int));
    
            var c4Parameter = c4.HasValue ?
                new ObjectParameter("c4", c4) :
                new ObjectParameter("c4", typeof(byte));
    
            var c5Parameter = c5.HasValue ?
                new ObjectParameter("c5", c5) :
                new ObjectParameter("c5", typeof(int));
    
            var c6Parameter = c6.HasValue ?
                new ObjectParameter("c6", c6) :
                new ObjectParameter("c6", typeof(int));
    
            var c7Parameter = c7 != null ?
                new ObjectParameter("c7", c7) :
                new ObjectParameter("c7", typeof(string));
    
            var c8Parameter = c8 != null ?
                new ObjectParameter("c8", c8) :
                new ObjectParameter("c8", typeof(string));
    
            var c9Parameter = c9 != null ?
                new ObjectParameter("c9", c9) :
                new ObjectParameter("c9", typeof(string));
    
            var c10Parameter = c10.HasValue ?
                new ObjectParameter("c10", c10) :
                new ObjectParameter("c10", typeof(decimal));
    
            var c11Parameter = c11.HasValue ?
                new ObjectParameter("c11", c11) :
                new ObjectParameter("c11", typeof(decimal));
    
            var c12Parameter = c12.HasValue ?
                new ObjectParameter("c12", c12) :
                new ObjectParameter("c12", typeof(decimal));
    
            var c13Parameter = c13.HasValue ?
                new ObjectParameter("c13", c13) :
                new ObjectParameter("c13", typeof(decimal));
    
            var c14Parameter = c14.HasValue ?
                new ObjectParameter("c14", c14) :
                new ObjectParameter("c14", typeof(decimal));
    
            var c15Parameter = c15.HasValue ?
                new ObjectParameter("c15", c15) :
                new ObjectParameter("c15", typeof(decimal));
    
            var c16Parameter = c16.HasValue ?
                new ObjectParameter("c16", c16) :
                new ObjectParameter("c16", typeof(decimal));
    
            var c17Parameter = c17.HasValue ?
                new ObjectParameter("c17", c17) :
                new ObjectParameter("c17", typeof(decimal));
    
            var c18Parameter = c18.HasValue ?
                new ObjectParameter("c18", c18) :
                new ObjectParameter("c18", typeof(decimal));
    
            var c19Parameter = c19.HasValue ?
                new ObjectParameter("c19", c19) :
                new ObjectParameter("c19", typeof(byte));
    
            var c20Parameter = c20.HasValue ?
                new ObjectParameter("c20", c20) :
                new ObjectParameter("c20", typeof(decimal));
    
            var c21Parameter = c21.HasValue ?
                new ObjectParameter("c21", c21) :
                new ObjectParameter("c21", typeof(decimal));
    
            var c22Parameter = c22.HasValue ?
                new ObjectParameter("c22", c22) :
                new ObjectParameter("c22", typeof(decimal));
    
            var c23Parameter = c23.HasValue ?
                new ObjectParameter("c23", c23) :
                new ObjectParameter("c23", typeof(decimal));
    
            var c24Parameter = c24.HasValue ?
                new ObjectParameter("c24", c24) :
                new ObjectParameter("c24", typeof(decimal));
    
            var c25Parameter = c25.HasValue ?
                new ObjectParameter("c25", c25) :
                new ObjectParameter("c25", typeof(decimal));
    
            var c26Parameter = c26.HasValue ?
                new ObjectParameter("c26", c26) :
                new ObjectParameter("c26", typeof(bool));
    
            var c27Parameter = c27.HasValue ?
                new ObjectParameter("c27", c27) :
                new ObjectParameter("c27", typeof(decimal));
    
            var c28Parameter = c28.HasValue ?
                new ObjectParameter("c28", c28) :
                new ObjectParameter("c28", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSins_dboPOSRetDet_msrepl_ccs", c1Parameter, c2Parameter, c3Parameter, c4Parameter, c5Parameter, c6Parameter, c7Parameter, c8Parameter, c9Parameter, c10Parameter, c11Parameter, c12Parameter, c13Parameter, c14Parameter, c15Parameter, c16Parameter, c17Parameter, c18Parameter, c19Parameter, c20Parameter, c21Parameter, c22Parameter, c23Parameter, c24Parameter, c25Parameter, c26Parameter, c27Parameter, c28Parameter);
        }
    
        public virtual int sp_MSins_dboPOSRetMst_msrepl_ccs(Nullable<int> c1, Nullable<int> c2, Nullable<int> c3, Nullable<System.DateTime> c4, Nullable<byte> c5, Nullable<byte> c6, Nullable<int> c7, Nullable<byte> c8, string c9, Nullable<System.DateTime> c10, Nullable<int> c11, string c12, Nullable<int> c13, Nullable<int> c14)
        {
            var c1Parameter = c1.HasValue ?
                new ObjectParameter("c1", c1) :
                new ObjectParameter("c1", typeof(int));
    
            var c2Parameter = c2.HasValue ?
                new ObjectParameter("c2", c2) :
                new ObjectParameter("c2", typeof(int));
    
            var c3Parameter = c3.HasValue ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(int));
    
            var c4Parameter = c4.HasValue ?
                new ObjectParameter("c4", c4) :
                new ObjectParameter("c4", typeof(System.DateTime));
    
            var c5Parameter = c5.HasValue ?
                new ObjectParameter("c5", c5) :
                new ObjectParameter("c5", typeof(byte));
    
            var c6Parameter = c6.HasValue ?
                new ObjectParameter("c6", c6) :
                new ObjectParameter("c6", typeof(byte));
    
            var c7Parameter = c7.HasValue ?
                new ObjectParameter("c7", c7) :
                new ObjectParameter("c7", typeof(int));
    
            var c8Parameter = c8.HasValue ?
                new ObjectParameter("c8", c8) :
                new ObjectParameter("c8", typeof(byte));
    
            var c9Parameter = c9 != null ?
                new ObjectParameter("c9", c9) :
                new ObjectParameter("c9", typeof(string));
    
            var c10Parameter = c10.HasValue ?
                new ObjectParameter("c10", c10) :
                new ObjectParameter("c10", typeof(System.DateTime));
    
            var c11Parameter = c11.HasValue ?
                new ObjectParameter("c11", c11) :
                new ObjectParameter("c11", typeof(int));
    
            var c12Parameter = c12 != null ?
                new ObjectParameter("c12", c12) :
                new ObjectParameter("c12", typeof(string));
    
            var c13Parameter = c13.HasValue ?
                new ObjectParameter("c13", c13) :
                new ObjectParameter("c13", typeof(int));
    
            var c14Parameter = c14.HasValue ?
                new ObjectParameter("c14", c14) :
                new ObjectParameter("c14", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSins_dboPOSRetMst_msrepl_ccs", c1Parameter, c2Parameter, c3Parameter, c4Parameter, c5Parameter, c6Parameter, c7Parameter, c8Parameter, c9Parameter, c10Parameter, c11Parameter, c12Parameter, c13Parameter, c14Parameter);
        }
    
        public virtual int sp_MSins_dboStock_Medical_msrepl_ccs(Nullable<int> c1, Nullable<int> c2, Nullable<int> c3, Nullable<int> c4, Nullable<System.DateTime> c5, string c6, Nullable<System.DateTime> c7, Nullable<int> c8, string c9, string c10, Nullable<byte> c11, Nullable<byte> c12, string c13, Nullable<decimal> c14, Nullable<decimal> c15, Nullable<decimal> c16, Nullable<decimal> c17, Nullable<decimal> c18, Nullable<decimal> c19, Nullable<decimal> c20, Nullable<decimal> c21, Nullable<decimal> c22, Nullable<int> c23, Nullable<decimal> c24, Nullable<decimal> c25, Nullable<decimal> c26, Nullable<decimal> c27, Nullable<decimal> c28, Nullable<decimal> c29, Nullable<decimal> c30, Nullable<decimal> c31, Nullable<decimal> c32, Nullable<decimal> c33, Nullable<decimal> c34, Nullable<decimal> c35, Nullable<decimal> c36, Nullable<decimal> c37, Nullable<decimal> c38, Nullable<decimal> c39, Nullable<decimal> c40, Nullable<bool> c41, Nullable<decimal> c42, Nullable<decimal> c43, Nullable<int> c44, Nullable<int> c45, string c46, string c47, string c48, Nullable<int> c49, string c50, Nullable<System.DateTime> c51)
        {
            var c1Parameter = c1.HasValue ?
                new ObjectParameter("c1", c1) :
                new ObjectParameter("c1", typeof(int));
    
            var c2Parameter = c2.HasValue ?
                new ObjectParameter("c2", c2) :
                new ObjectParameter("c2", typeof(int));
    
            var c3Parameter = c3.HasValue ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(int));
    
            var c4Parameter = c4.HasValue ?
                new ObjectParameter("c4", c4) :
                new ObjectParameter("c4", typeof(int));
    
            var c5Parameter = c5.HasValue ?
                new ObjectParameter("c5", c5) :
                new ObjectParameter("c5", typeof(System.DateTime));
    
            var c6Parameter = c6 != null ?
                new ObjectParameter("c6", c6) :
                new ObjectParameter("c6", typeof(string));
    
            var c7Parameter = c7.HasValue ?
                new ObjectParameter("c7", c7) :
                new ObjectParameter("c7", typeof(System.DateTime));
    
            var c8Parameter = c8.HasValue ?
                new ObjectParameter("c8", c8) :
                new ObjectParameter("c8", typeof(int));
    
            var c9Parameter = c9 != null ?
                new ObjectParameter("c9", c9) :
                new ObjectParameter("c9", typeof(string));
    
            var c10Parameter = c10 != null ?
                new ObjectParameter("c10", c10) :
                new ObjectParameter("c10", typeof(string));
    
            var c11Parameter = c11.HasValue ?
                new ObjectParameter("c11", c11) :
                new ObjectParameter("c11", typeof(byte));
    
            var c12Parameter = c12.HasValue ?
                new ObjectParameter("c12", c12) :
                new ObjectParameter("c12", typeof(byte));
    
            var c13Parameter = c13 != null ?
                new ObjectParameter("c13", c13) :
                new ObjectParameter("c13", typeof(string));
    
            var c14Parameter = c14.HasValue ?
                new ObjectParameter("c14", c14) :
                new ObjectParameter("c14", typeof(decimal));
    
            var c15Parameter = c15.HasValue ?
                new ObjectParameter("c15", c15) :
                new ObjectParameter("c15", typeof(decimal));
    
            var c16Parameter = c16.HasValue ?
                new ObjectParameter("c16", c16) :
                new ObjectParameter("c16", typeof(decimal));
    
            var c17Parameter = c17.HasValue ?
                new ObjectParameter("c17", c17) :
                new ObjectParameter("c17", typeof(decimal));
    
            var c18Parameter = c18.HasValue ?
                new ObjectParameter("c18", c18) :
                new ObjectParameter("c18", typeof(decimal));
    
            var c19Parameter = c19.HasValue ?
                new ObjectParameter("c19", c19) :
                new ObjectParameter("c19", typeof(decimal));
    
            var c20Parameter = c20.HasValue ?
                new ObjectParameter("c20", c20) :
                new ObjectParameter("c20", typeof(decimal));
    
            var c21Parameter = c21.HasValue ?
                new ObjectParameter("c21", c21) :
                new ObjectParameter("c21", typeof(decimal));
    
            var c22Parameter = c22.HasValue ?
                new ObjectParameter("c22", c22) :
                new ObjectParameter("c22", typeof(decimal));
    
            var c23Parameter = c23.HasValue ?
                new ObjectParameter("c23", c23) :
                new ObjectParameter("c23", typeof(int));
    
            var c24Parameter = c24.HasValue ?
                new ObjectParameter("c24", c24) :
                new ObjectParameter("c24", typeof(decimal));
    
            var c25Parameter = c25.HasValue ?
                new ObjectParameter("c25", c25) :
                new ObjectParameter("c25", typeof(decimal));
    
            var c26Parameter = c26.HasValue ?
                new ObjectParameter("c26", c26) :
                new ObjectParameter("c26", typeof(decimal));
    
            var c27Parameter = c27.HasValue ?
                new ObjectParameter("c27", c27) :
                new ObjectParameter("c27", typeof(decimal));
    
            var c28Parameter = c28.HasValue ?
                new ObjectParameter("c28", c28) :
                new ObjectParameter("c28", typeof(decimal));
    
            var c29Parameter = c29.HasValue ?
                new ObjectParameter("c29", c29) :
                new ObjectParameter("c29", typeof(decimal));
    
            var c30Parameter = c30.HasValue ?
                new ObjectParameter("c30", c30) :
                new ObjectParameter("c30", typeof(decimal));
    
            var c31Parameter = c31.HasValue ?
                new ObjectParameter("c31", c31) :
                new ObjectParameter("c31", typeof(decimal));
    
            var c32Parameter = c32.HasValue ?
                new ObjectParameter("c32", c32) :
                new ObjectParameter("c32", typeof(decimal));
    
            var c33Parameter = c33.HasValue ?
                new ObjectParameter("c33", c33) :
                new ObjectParameter("c33", typeof(decimal));
    
            var c34Parameter = c34.HasValue ?
                new ObjectParameter("c34", c34) :
                new ObjectParameter("c34", typeof(decimal));
    
            var c35Parameter = c35.HasValue ?
                new ObjectParameter("c35", c35) :
                new ObjectParameter("c35", typeof(decimal));
    
            var c36Parameter = c36.HasValue ?
                new ObjectParameter("c36", c36) :
                new ObjectParameter("c36", typeof(decimal));
    
            var c37Parameter = c37.HasValue ?
                new ObjectParameter("c37", c37) :
                new ObjectParameter("c37", typeof(decimal));
    
            var c38Parameter = c38.HasValue ?
                new ObjectParameter("c38", c38) :
                new ObjectParameter("c38", typeof(decimal));
    
            var c39Parameter = c39.HasValue ?
                new ObjectParameter("c39", c39) :
                new ObjectParameter("c39", typeof(decimal));
    
            var c40Parameter = c40.HasValue ?
                new ObjectParameter("c40", c40) :
                new ObjectParameter("c40", typeof(decimal));
    
            var c41Parameter = c41.HasValue ?
                new ObjectParameter("c41", c41) :
                new ObjectParameter("c41", typeof(bool));
    
            var c42Parameter = c42.HasValue ?
                new ObjectParameter("c42", c42) :
                new ObjectParameter("c42", typeof(decimal));
    
            var c43Parameter = c43.HasValue ?
                new ObjectParameter("c43", c43) :
                new ObjectParameter("c43", typeof(decimal));
    
            var c44Parameter = c44.HasValue ?
                new ObjectParameter("c44", c44) :
                new ObjectParameter("c44", typeof(int));
    
            var c45Parameter = c45.HasValue ?
                new ObjectParameter("c45", c45) :
                new ObjectParameter("c45", typeof(int));
    
            var c46Parameter = c46 != null ?
                new ObjectParameter("c46", c46) :
                new ObjectParameter("c46", typeof(string));
    
            var c47Parameter = c47 != null ?
                new ObjectParameter("c47", c47) :
                new ObjectParameter("c47", typeof(string));
    
            var c48Parameter = c48 != null ?
                new ObjectParameter("c48", c48) :
                new ObjectParameter("c48", typeof(string));
    
            var c49Parameter = c49.HasValue ?
                new ObjectParameter("c49", c49) :
                new ObjectParameter("c49", typeof(int));
    
            var c50Parameter = c50 != null ?
                new ObjectParameter("c50", c50) :
                new ObjectParameter("c50", typeof(string));
    
            var c51Parameter = c51.HasValue ?
                new ObjectParameter("c51", c51) :
                new ObjectParameter("c51", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSins_dboStock_Medical_msrepl_ccs", c1Parameter, c2Parameter, c3Parameter, c4Parameter, c5Parameter, c6Parameter, c7Parameter, c8Parameter, c9Parameter, c10Parameter, c11Parameter, c12Parameter, c13Parameter, c14Parameter, c15Parameter, c16Parameter, c17Parameter, c18Parameter, c19Parameter, c20Parameter, c21Parameter, c22Parameter, c23Parameter, c24Parameter, c25Parameter, c26Parameter, c27Parameter, c28Parameter, c29Parameter, c30Parameter, c31Parameter, c32Parameter, c33Parameter, c34Parameter, c35Parameter, c36Parameter, c37Parameter, c38Parameter, c39Parameter, c40Parameter, c41Parameter, c42Parameter, c43Parameter, c44Parameter, c45Parameter, c46Parameter, c47Parameter, c48Parameter, c49Parameter, c50Parameter, c51Parameter);
        }
    
        public virtual int sp_MSins_dboStockist_SaleInvoiceDet_1_msrepl_ccs(Nullable<int> c1, Nullable<int> c2, Nullable<int> c3, Nullable<int> c4, string c5, Nullable<byte> c6, Nullable<decimal> c7)
        {
            var c1Parameter = c1.HasValue ?
                new ObjectParameter("c1", c1) :
                new ObjectParameter("c1", typeof(int));
    
            var c2Parameter = c2.HasValue ?
                new ObjectParameter("c2", c2) :
                new ObjectParameter("c2", typeof(int));
    
            var c3Parameter = c3.HasValue ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(int));
    
            var c4Parameter = c4.HasValue ?
                new ObjectParameter("c4", c4) :
                new ObjectParameter("c4", typeof(int));
    
            var c5Parameter = c5 != null ?
                new ObjectParameter("c5", c5) :
                new ObjectParameter("c5", typeof(string));
    
            var c6Parameter = c6.HasValue ?
                new ObjectParameter("c6", c6) :
                new ObjectParameter("c6", typeof(byte));
    
            var c7Parameter = c7.HasValue ?
                new ObjectParameter("c7", c7) :
                new ObjectParameter("c7", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSins_dboStockist_SaleInvoiceDet_1_msrepl_ccs", c1Parameter, c2Parameter, c3Parameter, c4Parameter, c5Parameter, c6Parameter, c7Parameter);
        }
    
        public virtual int sp_MSins_dboStockist_SaleInvoiceDet_msrepl_ccs(Nullable<int> c1, Nullable<int> c2, Nullable<int> c3, Nullable<byte> c4, Nullable<int> c5, string c6, string c7, Nullable<byte> c8, Nullable<byte> c9, string c10, Nullable<byte> c11, string c12, Nullable<decimal> c13, Nullable<decimal> c14, Nullable<decimal> c15, Nullable<decimal> c16, Nullable<decimal> c17, Nullable<decimal> c18, Nullable<decimal> c19, Nullable<decimal> c20, Nullable<decimal> c21, Nullable<decimal> c22, Nullable<decimal> c23, Nullable<decimal> c24, Nullable<decimal> c25, Nullable<decimal> c26, Nullable<int> c27, Nullable<byte> c28, Nullable<decimal> c29, Nullable<decimal> c30, Nullable<decimal> c31, Nullable<decimal> c32, Nullable<decimal> c33, Nullable<decimal> c34, Nullable<decimal> c35, Nullable<bool> c36, string c37)
        {
            var c1Parameter = c1.HasValue ?
                new ObjectParameter("c1", c1) :
                new ObjectParameter("c1", typeof(int));
    
            var c2Parameter = c2.HasValue ?
                new ObjectParameter("c2", c2) :
                new ObjectParameter("c2", typeof(int));
    
            var c3Parameter = c3.HasValue ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(int));
    
            var c4Parameter = c4.HasValue ?
                new ObjectParameter("c4", c4) :
                new ObjectParameter("c4", typeof(byte));
    
            var c5Parameter = c5.HasValue ?
                new ObjectParameter("c5", c5) :
                new ObjectParameter("c5", typeof(int));
    
            var c6Parameter = c6 != null ?
                new ObjectParameter("c6", c6) :
                new ObjectParameter("c6", typeof(string));
    
            var c7Parameter = c7 != null ?
                new ObjectParameter("c7", c7) :
                new ObjectParameter("c7", typeof(string));
    
            var c8Parameter = c8.HasValue ?
                new ObjectParameter("c8", c8) :
                new ObjectParameter("c8", typeof(byte));
    
            var c9Parameter = c9.HasValue ?
                new ObjectParameter("c9", c9) :
                new ObjectParameter("c9", typeof(byte));
    
            var c10Parameter = c10 != null ?
                new ObjectParameter("c10", c10) :
                new ObjectParameter("c10", typeof(string));
    
            var c11Parameter = c11.HasValue ?
                new ObjectParameter("c11", c11) :
                new ObjectParameter("c11", typeof(byte));
    
            var c12Parameter = c12 != null ?
                new ObjectParameter("c12", c12) :
                new ObjectParameter("c12", typeof(string));
    
            var c13Parameter = c13.HasValue ?
                new ObjectParameter("c13", c13) :
                new ObjectParameter("c13", typeof(decimal));
    
            var c14Parameter = c14.HasValue ?
                new ObjectParameter("c14", c14) :
                new ObjectParameter("c14", typeof(decimal));
    
            var c15Parameter = c15.HasValue ?
                new ObjectParameter("c15", c15) :
                new ObjectParameter("c15", typeof(decimal));
    
            var c16Parameter = c16.HasValue ?
                new ObjectParameter("c16", c16) :
                new ObjectParameter("c16", typeof(decimal));
    
            var c17Parameter = c17.HasValue ?
                new ObjectParameter("c17", c17) :
                new ObjectParameter("c17", typeof(decimal));
    
            var c18Parameter = c18.HasValue ?
                new ObjectParameter("c18", c18) :
                new ObjectParameter("c18", typeof(decimal));
    
            var c19Parameter = c19.HasValue ?
                new ObjectParameter("c19", c19) :
                new ObjectParameter("c19", typeof(decimal));
    
            var c20Parameter = c20.HasValue ?
                new ObjectParameter("c20", c20) :
                new ObjectParameter("c20", typeof(decimal));
    
            var c21Parameter = c21.HasValue ?
                new ObjectParameter("c21", c21) :
                new ObjectParameter("c21", typeof(decimal));
    
            var c22Parameter = c22.HasValue ?
                new ObjectParameter("c22", c22) :
                new ObjectParameter("c22", typeof(decimal));
    
            var c23Parameter = c23.HasValue ?
                new ObjectParameter("c23", c23) :
                new ObjectParameter("c23", typeof(decimal));
    
            var c24Parameter = c24.HasValue ?
                new ObjectParameter("c24", c24) :
                new ObjectParameter("c24", typeof(decimal));
    
            var c25Parameter = c25.HasValue ?
                new ObjectParameter("c25", c25) :
                new ObjectParameter("c25", typeof(decimal));
    
            var c26Parameter = c26.HasValue ?
                new ObjectParameter("c26", c26) :
                new ObjectParameter("c26", typeof(decimal));
    
            var c27Parameter = c27.HasValue ?
                new ObjectParameter("c27", c27) :
                new ObjectParameter("c27", typeof(int));
    
            var c28Parameter = c28.HasValue ?
                new ObjectParameter("c28", c28) :
                new ObjectParameter("c28", typeof(byte));
    
            var c29Parameter = c29.HasValue ?
                new ObjectParameter("c29", c29) :
                new ObjectParameter("c29", typeof(decimal));
    
            var c30Parameter = c30.HasValue ?
                new ObjectParameter("c30", c30) :
                new ObjectParameter("c30", typeof(decimal));
    
            var c31Parameter = c31.HasValue ?
                new ObjectParameter("c31", c31) :
                new ObjectParameter("c31", typeof(decimal));
    
            var c32Parameter = c32.HasValue ?
                new ObjectParameter("c32", c32) :
                new ObjectParameter("c32", typeof(decimal));
    
            var c33Parameter = c33.HasValue ?
                new ObjectParameter("c33", c33) :
                new ObjectParameter("c33", typeof(decimal));
    
            var c34Parameter = c34.HasValue ?
                new ObjectParameter("c34", c34) :
                new ObjectParameter("c34", typeof(decimal));
    
            var c35Parameter = c35.HasValue ?
                new ObjectParameter("c35", c35) :
                new ObjectParameter("c35", typeof(decimal));
    
            var c36Parameter = c36.HasValue ?
                new ObjectParameter("c36", c36) :
                new ObjectParameter("c36", typeof(bool));
    
            var c37Parameter = c37 != null ?
                new ObjectParameter("c37", c37) :
                new ObjectParameter("c37", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSins_dboStockist_SaleInvoiceDet_msrepl_ccs", c1Parameter, c2Parameter, c3Parameter, c4Parameter, c5Parameter, c6Parameter, c7Parameter, c8Parameter, c9Parameter, c10Parameter, c11Parameter, c12Parameter, c13Parameter, c14Parameter, c15Parameter, c16Parameter, c17Parameter, c18Parameter, c19Parameter, c20Parameter, c21Parameter, c22Parameter, c23Parameter, c24Parameter, c25Parameter, c26Parameter, c27Parameter, c28Parameter, c29Parameter, c30Parameter, c31Parameter, c32Parameter, c33Parameter, c34Parameter, c35Parameter, c36Parameter, c37Parameter);
        }
    
        public virtual int sp_MSins_dboStockist_SaleInvoiceMst_msrepl_ccs(Nullable<int> c1, Nullable<int> c2, Nullable<System.DateTime> c3, string c4, Nullable<int> c5, Nullable<int> c6, Nullable<System.DateTime> c7, Nullable<int> c8, Nullable<System.DateTime> c9, Nullable<int> c10, Nullable<System.DateTime> c11, string c12, string c13, string c14, string c15, Nullable<System.DateTime> c16, Nullable<int> c17, string c18, Nullable<int> c19, Nullable<int> c20, Nullable<byte> c21, Nullable<int> c22)
        {
            var c1Parameter = c1.HasValue ?
                new ObjectParameter("c1", c1) :
                new ObjectParameter("c1", typeof(int));
    
            var c2Parameter = c2.HasValue ?
                new ObjectParameter("c2", c2) :
                new ObjectParameter("c2", typeof(int));
    
            var c3Parameter = c3.HasValue ?
                new ObjectParameter("c3", c3) :
                new ObjectParameter("c3", typeof(System.DateTime));
    
            var c4Parameter = c4 != null ?
                new ObjectParameter("c4", c4) :
                new ObjectParameter("c4", typeof(string));
    
            var c5Parameter = c5.HasValue ?
                new ObjectParameter("c5", c5) :
                new ObjectParameter("c5", typeof(int));
    
            var c6Parameter = c6.HasValue ?
                new ObjectParameter("c6", c6) :
                new ObjectParameter("c6", typeof(int));
    
            var c7Parameter = c7.HasValue ?
                new ObjectParameter("c7", c7) :
                new ObjectParameter("c7", typeof(System.DateTime));
    
            var c8Parameter = c8.HasValue ?
                new ObjectParameter("c8", c8) :
                new ObjectParameter("c8", typeof(int));
    
            var c9Parameter = c9.HasValue ?
                new ObjectParameter("c9", c9) :
                new ObjectParameter("c9", typeof(System.DateTime));
    
            var c10Parameter = c10.HasValue ?
                new ObjectParameter("c10", c10) :
                new ObjectParameter("c10", typeof(int));
    
            var c11Parameter = c11.HasValue ?
                new ObjectParameter("c11", c11) :
                new ObjectParameter("c11", typeof(System.DateTime));
    
            var c12Parameter = c12 != null ?
                new ObjectParameter("c12", c12) :
                new ObjectParameter("c12", typeof(string));
    
            var c13Parameter = c13 != null ?
                new ObjectParameter("c13", c13) :
                new ObjectParameter("c13", typeof(string));
    
            var c14Parameter = c14 != null ?
                new ObjectParameter("c14", c14) :
                new ObjectParameter("c14", typeof(string));
    
            var c15Parameter = c15 != null ?
                new ObjectParameter("c15", c15) :
                new ObjectParameter("c15", typeof(string));
    
            var c16Parameter = c16.HasValue ?
                new ObjectParameter("c16", c16) :
                new ObjectParameter("c16", typeof(System.DateTime));
    
            var c17Parameter = c17.HasValue ?
                new ObjectParameter("c17", c17) :
                new ObjectParameter("c17", typeof(int));
    
            var c18Parameter = c18 != null ?
                new ObjectParameter("c18", c18) :
                new ObjectParameter("c18", typeof(string));
    
            var c19Parameter = c19.HasValue ?
                new ObjectParameter("c19", c19) :
                new ObjectParameter("c19", typeof(int));
    
            var c20Parameter = c20.HasValue ?
                new ObjectParameter("c20", c20) :
                new ObjectParameter("c20", typeof(int));
    
            var c21Parameter = c21.HasValue ?
                new ObjectParameter("c21", c21) :
                new ObjectParameter("c21", typeof(byte));
    
            var c22Parameter = c22.HasValue ?
                new ObjectParameter("c22", c22) :
                new ObjectParameter("c22", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSins_dboStockist_SaleInvoiceMst_msrepl_ccs", c1Parameter, c2Parameter, c3Parameter, c4Parameter, c5Parameter, c6Parameter, c7Parameter, c8Parameter, c9Parameter, c10Parameter, c11Parameter, c12Parameter, c13Parameter, c14Parameter, c15Parameter, c16Parameter, c17Parameter, c18Parameter, c19Parameter, c20Parameter, c21Parameter, c22Parameter);
        }
    
        public virtual ObjectResult<GetAllProductsAPI_Result> GetAllProductsAPI(string type, Nullable<int> userId)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllProductsAPI_Result>("GetAllProductsAPI", typeParameter, userIdParameter);
        }
    }
}
