//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportMst
    {
        public int ReportMstID { get; set; }
        public Nullable<int> TestCode { get; set; }
        public Nullable<int> ReportTypeCode { get; set; }
        public int ReportCode { get; set; }
        public string ReportName { get; set; }
        public string ReportHeading { get; set; }
        public string ReportPath { get; set; }
        public Nullable<int> SortID { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
