//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInvoiceDet_1
    {
        public int SaleInvoiceDetID_1 { get; set; }
        public Nullable<int> SaleInvoiceMstID { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public Nullable<int> ProductCode_1 { get; set; }
        public string BatchNo { get; set; }
        public Nullable<byte> Srno { get; set; }
        public Nullable<decimal> Qty { get; set; }
    }
}
