//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Medical
    {
        public int MedcalStockMstID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<int> BCode { get; set; }
        public Nullable<int> BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public Nullable<int> ProductCode { get; set; }
        public string BatchNo { get; set; }
        public string ExpiryDate { get; set; }
        public Nullable<byte> GodownCode { get; set; }
        public Nullable<byte> RackCode { get; set; }
        public string Box { get; set; }
        public Nullable<decimal> QtyInUnit { get; set; }
        public Nullable<decimal> QtyInStrip { get; set; }
        public Nullable<decimal> QtyInBox { get; set; }
        public Nullable<decimal> QtyInCartoon { get; set; }
        public Nullable<decimal> PurRetQtyInUnit { get; set; }
        public Nullable<decimal> PurRetQtyInStrip { get; set; }
        public Nullable<decimal> PurRetQtyInBox { get; set; }
        public Nullable<decimal> PurRetQtyInCartoon { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> PurRate { get; set; }
        public Nullable<decimal> PurAmt { get; set; }
        public Nullable<decimal> PurDisc { get; set; }
        public Nullable<decimal> PurDiscAmt { get; set; }
        public Nullable<int> MarginMstID { get; set; }
        public Nullable<decimal> PurGst { get; set; }
        public Nullable<decimal> PurGstAmt { get; set; }
        public Nullable<decimal> SalQtyInUnit { get; set; }
        public Nullable<decimal> SalQtyInStrip { get; set; }
        public Nullable<decimal> SalQtyInBox { get; set; }
        public Nullable<decimal> SalQtyInCartoon { get; set; }
        public Nullable<decimal> SalRate { get; set; }
        public Nullable<decimal> SalAmt { get; set; }
        public Nullable<decimal> SalDisc { get; set; }
        public Nullable<decimal> SalDiscAmt { get; set; }
        public Nullable<decimal> SalCGST { get; set; }
        public Nullable<decimal> SalCAMT { get; set; }
        public Nullable<decimal> SalSGST { get; set; }
        public Nullable<decimal> SalSAmt { get; set; }
        public Nullable<decimal> SalGst { get; set; }
        public Nullable<decimal> SalGstAmt { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public Nullable<bool> PurFreeProduct { get; set; }
        public Nullable<decimal> CustRetQtyInUnit { get; set; }
        public Nullable<decimal> CustRetQtyInStrip { get; set; }
        public Nullable<int> DetID { get; set; }
        public Nullable<int> MstID { get; set; }
        public string Process { get; set; }
        public string FormName { get; set; }
        public string TableName { get; set; }
        public Nullable<int> LogID { get; set; }
        public string PcID { get; set; }
        public Nullable<System.DateTime> Sdate { get; set; }
    }
}
