//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageMst
    {
        public byte StorageMstID { get; set; }
        public byte StorageCode { get; set; }
        public string StorageName { get; set; }
        public Nullable<byte> SortID { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
