//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxMst()
        {
            this.Med_PurchaseReturnDet = new HashSet<Med_PurchaseReturnDet>();
            this.Stockist_SaleInvoiceDet = new HashSet<Stockist_SaleInvoiceDet>();
            this.Stockist_SaleReturnDet = new HashSet<Stockist_SaleReturnDet>();
        }
    
        public int TaxMstID { get; set; }
        public byte TaxCode { get; set; }
        public string TaxName { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<int> SortID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Sflag { get; set; }
        public Nullable<System.DateTime> Sdate { get; set; }
        public Nullable<int> LogID { get; set; }
        public string PcID { get; set; }
        public Nullable<int> Ever { get; set; }
        public Nullable<int> CompanyCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Med_PurchaseReturnDet> Med_PurchaseReturnDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stockist_SaleInvoiceDet> Stockist_SaleInvoiceDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stockist_SaleReturnDet> Stockist_SaleReturnDet { get; set; }
    }
}
