//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductWebAPI_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpGiftReportMst
    {
        public int GiftMstID { get; set; }
        public Nullable<System.DateTime> GiftDate { get; set; }
        public string GiftTime { get; set; }
        public Nullable<int> BillNo { get; set; }
        public Nullable<decimal> BillAmt { get; set; }
        public string Name { get; set; }
        public string MobNo { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string Branch { get; set; }
        public Nullable<int> Giftvalue { get; set; }
        public string Gift { get; set; }
    }
}
